force-app/main/default/objects/Declarative_task__mdt/Declarative_task__mdt.object-meta.xml
<CustomObject>
    <description>Setup data for task generation button</description>
    <label>Declarative task</label>
    <pluralLabel>Declarative tasks</pluralLabel>
</CustomObject>

force-app/main/default/objects/Declarative_task__mdt/fields/assign_to__c.field-meta.xml
<CustomField>
    <fullName>assign_to__c</fullName>
    <description>required task field...</description>
    <label>assign to</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Declarative_task__mdt/fields/objectAPIName__c.field-meta.xml
<CustomField>
    <fullName>objectAPIName__c</fullName>
    <label>objectAPIName</label>
    <referenceTo>EntityDefinition</referenceTo>
    <relationshipLabel>Declarative_tasks</relationshipLabel>
    <relationshipName>Declarative_tasks</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Declarative_task__mdt/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <label>Priority</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>high</fullName>
                <default>true</default>
                <label>high</label>
            </value>
            <value>
                <fullName>normal</fullName>
            </value>
            <value>
                <fullName>low</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Declarative_task__mdt/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
                <default>true</default>
                <label>Not Started</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Waiting on someone else</fullName>
            </value>
            <value>
                <fullName>Deferred</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Declarative_task__mdt/fields/subject__c.field-meta.xml
<CustomField>
    <fullName>subject__c</fullName>
    <inlineHelpText>...</inlineHelpText>
    <label>subject</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CreateTaskController.cls
public with sharing class CreateTaskController {
    
    Sobject record; 
    String objectAPIName;
    Declarative_task__mdt taskGen;
    
    //Do stuff...
    public void run() {      
        queryRecord();
        createTask();      
    }
    
    private void createTask(){
        Task t = new Task();
        
        t.Status = taskGen.Status__c;
        t.Subject = taskGen.subject__c;
        t.Priority = taskGen.Priority__c;
        
        t.OwnerId = UserInfo.getUserId();
        t.whatid = record.id;

        insert t;            
    }
    
    //query for record...
    private void queryRecord(){
        ID s =(Id) ApexPages.currentPage().getParameters().get('id');
        objectAPIName = s.getSObjectType().getDescribe().getName();
        String query = 'SELECT id from ' + objectAPIName + ' where id = \''  + s +    '\' limit 1 ';
        String taskQuery = getFieldString();
        
        try{
        record = Database.query(query)[0];
        taskGen = [SELECT Fields(STANDARD),
                    Status__c , 
                    subject__c , 
                    Priority__c , 
                    assign_to__c 
                    FROM Declarative_task__mdt where objectAPIName__c = :objectAPIName limit 1][0];

        }catch (exception e){
            //System.debug(e);
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, e.getMessage()));    
        }
    }

    //Helper method to dynamically get all fields on Custom Metadata Type
    public static String getFieldString(){
        declarative_task__mdt dtm = new declarative_task__mdt();
        Sobjecttype dtmtype = dtm.getSObjectType();
        Map<String,Schema.SObjectField> mfields = dtmtype.getDescribe().fields.getMap();   
        
        String dynamicQuery = 'SELECT ';
        for (String s : mfields.keySet()){
            dynamicQuery +=  s + ',';
        }
        dynamicQuery = dynamicQuery.removeEndIgnoreCase(',');

        return dynamicQuery;
    }


    
}